require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.impatient"
require "user.indentline"
require "user.alpha"
require "user.whichkey"
require "user.autocommands"
-- on test
require "user.onedark"
require "user.quickscope"
require "user.hop"
require "user.colorizer"
require "user.spectre"
require "user.neoscroll"
require "user.notify"
require "user.session-manager"
require "user.ts-context"
require "user.telescope-file-browser"
require "user.functions"

-- require "user.gist"
-- require "user.gitlinker"
-- require "user.matchup"
-- require "user.numb"
-- require "user.dial"
-- require "user.zen-mode"
-- require "user.todo-comments"
-- require "user.bookmark"
-- require "user.renamer" -- LSP
-- require "user.symbol-outline" -- LSP
-- require "user.surround"
-- require "user.registers"
-- require "user.sniprun"
-- require "user.copilot"
-- require "user.gps"
-- require "user.illuminate"
-- require "user.git-blame"
